# Site
name: "Roll Along"
title: "Roll Along"
description: "Roll Along: a travel adventure"
logo: 'assets/images/Scamp-white.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: john@rkroll.com

menu: 
  - "Home"
  - "About"

# Authors
authors:
  john:
    name: John
    display_name: John
    gravatar: fc1792b16d25a164ff8e46354c884cc3
    email: john@rkroll.com
    web: ''
    description: "One half of John & Rae's adventure"
  rachel:
    name: Rachel
    display_name: Rachel    
    avatar: ''
    gravatar: ''
    email: rkroll@rkroll.com
    web: ''
    description: "One half of John & Rae's adventure"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
